# Set theme
theme: alembic-jekyll-theme
# 
exclude:
-
 _redirects
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
# Site settings
title: 'shares'
description: 'Shares Android apps & Tutorials'
baseurl: ''
url: 'https://shares.netlify.com'
# permalink: pretty
logo: "https://shares.netlify.com/img/androids.png"
#
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Hyde"
      permalink: /:pth
     # 
baseurl: ''
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body] 
