# Set theme
theme: alembic-jekyll-theme
# 
exclude:
-
 _redirects
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
# Site settings
title: 'shares'
description: 'Shares Android apps & Tutorials'
baseurl: ''
url: 'https://shares.netlify.com'
# permalink: pretty
logo: "https://shares.netlify.com/img/androids.png"
#
collections_dir: pages
#
collections:
pages:
output: true
    permalink: /:path/
   # 
  defaults:
  -
    scope:
      path: ""
      type: "facebook"
    values:
      layout: "fb"
   -
     scope:
      path: ""
      type: "link2app"
    values:
      layout: "link2app-layout"
         -
     scope:
      path: ""
      type: "oiin"
    values:
      layout: "oiin-layout"
     # 
baseurl: ''
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body] 
